In [24]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [27]:
x_train = np.array([[2104, 5, 1, 45],
                   [1416, 3, 2, 40],
                    [852, 2, 1, 35]])


y_train = np.array([460, 232, 178])

print(f"Shape of x_train: {x_train.shape}\n Shape of y_train: {y_train.shape}")


Shape of x_train: (3, 4)
 Shape of y_train: (3,)


In [40]:
print(x_train)
print(f"Type of x_train: {type(x_train)}")
print(y_train)
print(f"Type of y_train: {type(y_train)}")


[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Type of x_train: <class 'numpy.ndarray'>
[460 232 178]
Type of y_train: <class 'numpy.ndarray'>


In [41]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [42]:
def predict_with_loop(x, w, b):
    res = b

    for i in range(w.shape[0]):
        res += w[i] * x[i]

    return res


In [44]:
# get a row from our training data
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict_with_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194081


In [45]:
def predict(x, w, b):
    return np.dot(w, x) + b

In [46]:
# get a row from our training data
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [47]:
def compute_cost(x, y, w, b):
    total = 0
    m = x.shape[0]
    for i in range(m):
        y_estimate = predict(x[i], w, b)
        diff = (y_estimate - y[i]) ** 2
        total += diff

    result = total / (2 *m)
    return result

In [48]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f"The cost: {cost}")

The cost: 1.5578904428966628e-12


In [49]:
def compute_gradient(x, y ,w, b):
    m,n = x.shape
    dj_dw = np.zeros(n)
    dj_db = 0

    for i in range(m):
        y_estimate = predict(x[i], w, b)
        diff = y_estimate - y[i]
        dj_db +=  diff
        for j in range(n):
            dj_dw[j] += diff * x[i][j]

    dj_dw /= m
    dj_db /= m

    return dj_db, dj_dw

In [50]:
#Compute and display gradient 
tmp_dj_db, tmp_dj_dw = compute_gradient(x_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251501955248e-06
dj_dw at initial w,b: 
 [-2.72623577e-03 -6.27197263e-06 -2.21745578e-06 -6.92403391e-05]


In [51]:
def gradient_descent(x, y, w_in, b_in, learning_rate, num_iters):
    m,n = x.shape
    w = w_in
    b = b_in
    j_history = []

    for i in range(num_iters):
        dj_db, dj_dw = compute_gradient(x, y, w, b)
        w -= learning_rate * dj_dw
        b -= learning_rate * dj_db

        if i < 100000:
            j_history.append(compute_cost(x,y, w, b))

        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {j_history[-1]:8.2f}   ")

    return w, b, j_history

In [53]:
# initialize parameters
initial_w = np.zeros_like(w_init)
initial_b = 0.
# some gradient descent settings
iterations = 1000
alpha = 5.0e-7
# run gradient descent 
w_final, b_final, J_hist = gradient_descent(x_train, y_train, initial_w, initial_b, alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = x_train.shape
for i in range(m):
    print(f"prediction: {np.dot(x_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0: Cost  2529.46   
Iteration  100: Cost   695.99   
Iteration  200: Cost   694.92   
Iteration  300: Cost   693.86   
Iteration  400: Cost   692.81   
Iteration  500: Cost   691.77   
Iteration  600: Cost   690.73   
Iteration  700: Cost   689.71   
Iteration  800: Cost   688.70   
Iteration  900: Cost   687.69   
b,w found by gradient descent: -0.00,[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178
