In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x_train = np.array([[2104, 5, 1, 45],
                   [1416, 3, 2, 40],
                    [852, 2, 1, 35]])


y_train = np.array([460, 232, 178])

print(f"Shape of x_train: {x_train.shape}\n Shape of y_train: {y_train.shape}")


Shape of x_train: (3, 4)
 Shape of y_train: (3,)


In [7]:
print(x_train)
print(f"Type of x_train: {type(x_train)}")
print(y_train)
print(f"Type of y_train: {type(y_train)}")


[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Type of x_train: <class 'numpy.ndarray'>
[460 232 178]
Type of y_train: <class 'numpy.ndarray'>


In [8]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [10]:
def predict_with_loop(x, w, b):
    res = b

    for i in range(w.shape[0]):
        res += w[i] * x[i]

    return res


In [11]:
# get a row from our training data
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict_with_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194081


In [15]:
def predict(x, w, b):
    return np.dot(w, x) + b

In [16]:
# get a row from our training data
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

# make a prediction
f_wb = predict(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [17]:
def compute_cost(x, y, w, b):
    total = 0
    m = x.shape[0]
    for i in range(m):
        y_estimate = predict(x[i], w, b)
        diff = (y_estimate - y[i]) ** 2
        total += diff

    result = total / (2 *m)
    return result

In [18]:
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f"The cost: {cost}")

The cost: 1.5578904428966628e-12


In [ ]:
def compute_gradient(x, y ,w, b):
    dj_dw = 0
    m = x.shape[0]

    for i in range(m):
        for j in range(w.shape[0]):
        y_estimate = predict(x[i], w, b)
        diff = y_estimate - y[i]
        dj_dw += diff * x