In [17]:
import numpy as np
import tensorflow as tf
from lab_coffee_utils import load_coffee_data
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [18]:
X, y = load_coffee_data()
print(X.shape, y.shape)

(200, 2) (200, 1)


In [19]:
normalization_layer = tf.keras.layers.Normalization(axis=-1)
normalization_layer.adapt(X)
X_norm = normalization_layer(X)

In [20]:
Xt = np.tile(X_norm,(1000,1))
Yt= np.tile(y,(1000,1))   

In [21]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [tf.keras.Input((2,)),
    Dense(units=3, activation="sigmoid", name = "layer1"),
    Dense(units=1, activation="sigmoid", name = "layer2")]
)

In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                  │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer2 (Dense)                  │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print(f"W1{W1.shape}:\n", W1, f"\nb1{b1.shape}:", b1)
print(f"W2{W2.shape}:\n", W2, f"\nb2{b2.shape}:", b2)

W1(2, 3):
 [[-0.11 -1.03  0.28]
 [ 0.14  0.92 -0.61]] 
b1(3,): [0. 0. 0.]
W2(3, 1):
 [[-1.1 ]
 [ 0.21]
 [ 0.82]] 
b2(1,): [0.]


In [24]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),
)

In [25]:
model.fit(
    Xt,Yt,            
    epochs=10,
)

Epoch 1/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 8s 1ms/step - loss: 0.1844
Epoch 2/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 0.1291
Epoch 3/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 0.1160
Epoch 4/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 0.0414
Epoch 5/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 0.0167
Epoch 6/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 0.0109
Epoch 7/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 0.0077
Epoch 8/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 0.0055
Epoch 9/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 16s 3ms/step - loss: 0.0039
Epoch 10/10
6250/6250 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 0.0029


In [26]:
W1, b1 = model.get_layer("layer1").get_weights()
W2, b2 = model.get_layer("layer2").get_weights()
print("W1:\n", W1, "\nb1:", b1)
print("W2:\n", W2, "\nb2:", b2)

W1:
 [[ -0.02 -10.64 -17.35]
 [ -8.54  -0.19 -14.57]] 
b1: [-10.67 -11.65  -2.58]
W2:
 [[-42.49]
 [-46.89]
 [ 33.4 ]] 
b2: [-9.1]


In [28]:
X_test = np.array([
    [200,13.9],  # positive example
    [200,17]])   # negative example
X_testn = normalization_layer(X_test)
predictions = model.predict(X_testn)
print("predictions = \n", predictions, "\nType: ", type(predictions))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
predictions = 
 [[9.58e-01]
 [1.09e-04]] 
Type:  <class 'numpy.ndarray'>
